### ISSUE TITLE
Compose screen Changes

### ISSUE THREAD

**Issue by rhp1671** [3Einstens/CookMeNow#103]
If coming in from MyList:  
- [x] Remove the 'challenge recipe' overlap from the Recipe Title and make it the activity title
- [x] Make the RecipeTitle a TextView with a thumbnail and make it clickable if coming 
- [x] Clicking the RecipeTitle will take you to the Recipe description page and if you hit back from recipe description, it will take you back to the compose screen (the idea being to  provide instructions during compose if it is a challenge recipe)

**Comment by hideki** [comment]
![pasted image at 2017_04_24 12_34 pm](https://cloud.githubusercontent.com/assets/15889/25355318/0d0785a0-28eb-11e7-8a53-69e9570e23d5.png)
